---
- hosts: "{{vplex}}"
  gather_facts: false
#  connection: local
  tasks:
    - debug: msg="{{xio.user}}"
      delegate_to: localhost
    
    - debug: msg="{{xio.ip}}"
      delegate_to: localhost
        